spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booklibrary

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.homework3.mongock.changelog
